# DonutCore - Konfiguration (Deutsch) - MC 1.21.5 Nerfed Economy
settings:
  shard-per-kill: 8
  spawner-cost-multiplier: 1.1
  scoreboard-update-ticks: 20
  default-money: 0.0
  # Key-Preise mit Geld (Money) - Nerfed
  key-price:
    basic: 60
    rare: 250
    legendary: 900
  # Key-Preise mit Shards - Nerfed
  key-price-shards:
    basic: 30
    rare: 140
    legendary: 450
  crate-tiers:
    basic:
      enchant-level: 2
      enchant-chance: 0.6
      min-enchants: 1
      max-enchants: 2
    rare:
      enchant-level: 3
      enchant-chance: 0.8
      min-enchants: 2
      max-enchants: 4
    legendary:
      enchant-level: 5
      enchant-chance: 1.0
      min-enchants: 4
      max-enchants: 6
allowed-spawners:
  - ZOMBIE
  - SKELETON
  - CREEPER

# Comprehensive Worth Table for MC 1.21.5 - Nerfed Economy
worth:
  # Ores & Raw Materials (Nerfed)
  DIAMOND: 50
  EMERALD: 2
  IRON_INGOT: 1
  GOLD_INGOT: 1
  COAL: 2.5
  COPPER_INGOT: 6
  LAPIS_LAZULI: 2
  REDSTONE: 10
  QUARTZ: 1
  AMETHYST_SHARD: 5
  NETHERITE_INGOT: 2200
  NETHERITE_SCRAP: 500
  RAW_IRON: 8
  RAW_GOLD: 10
  RAW_COPPER: 8
  ANCIENT_DEBRIS: 250
  
  # Rare Items (Nerfed)
  NETHER_STAR: 5000
  ENCHANTED_GOLDEN_APPLE: 2000
  GOLDEN_APPLE: 4
  TOTEM_OF_UNDYING: 350
  ELYTRA: 25000
  TRIDENT: 5000
  SHULKER_SHELL: 10
  ENDER_PEARL: 5
  BLAZE_ROD: 0.50
  GHAST_TEAR: 6
  WITHER_SKELETON_SKULL: 400
  DRAGON_BREATH: 3
  END_CRYSTAL: 10
  BEACON: 5000
  CONDUIT: 1500
  HEART_OF_THE_SEA: 200
  NAUTILUS_SHELL: 60
  TURTLE_EGG: 20
  SPAWNER: 0
  DRAGON_EGG: 10000000
  DRAGON_HEAD: 200
  
  # Music Discs
  MUSIC_DISC_13: 90
  MUSIC_DISC_CAT: 90
  MUSIC_DISC_BLOCKS: 90
  MUSIC_DISC_CHIRP: 90
  MUSIC_DISC_FAR: 90
  MUSIC_DISC_MALL: 90
  MUSIC_DISC_MELLOHI: 90
  MUSIC_DISC_STAL: 90
  MUSIC_DISC_STRAD: 90
  MUSIC_DISC_WARD: 90
  MUSIC_DISC_11: 90
  MUSIC_DISC_WAIT: 90
  MUSIC_DISC_OTHERSIDE: 90
  MUSIC_DISC_5: 90
  MUSIC_DISC_PIGSTEP: 90
  MUSIC_DISC_RELIC: 90
  MUSIC_DISC_PRECIPICE: 90
  MUSIC_DISC_CREATOR: 90
  MUSIC_DISC_CREATOR_MUSIC_BOX: 90
  
  # 1.21/1.21.5 New Items
  MACE: 8000
  HEAVY_CORE: 3000
  BREEZE_ROD: 25
  WIND_CHARGE: 20
  TRIAL_KEY: 750
  OMINOUS_TRIAL_KEY: 1500
  OMINOUS_BOTTLE: 10
  
  # Common Blocks (Low Values)
  DIRT: 1
  GRASS_BLOCK: 1
  STONE: 1
  COBBLESTONE: 1
  GRAVEL: 1
  SAND: 1
  RED_SAND: 1
  ANDESITE: 1
  DIORITE: 1
  GRANITE: 1
  CALCITE: 1
  TUFF: 1
  DEEPSLATE: 1
  NETHERRACK: 1
  END_STONE: 1
  BASALT: 1
  BLACKSTONE: 1
  
  # Wood Types
  OAK_LOG: 16
  SPRUCE_LOG: 16
  BIRCH_LOG: 16
  JUNGLE_LOG: 16
  ACACIA_LOG: 16
  DARK_OAK_LOG: 16
  MANGROVE_LOG: 16
  CHERRY_LOG: 16
  BAMBOO_BLOCK: 16
  CRIMSON_STEM: 16  
  WARPED_STEM: 16
  OAK_PLANKS: 16
  SPRUCE_PLANKS: 16
  BIRCH_PLANKS: 16
  JUNGLE_PLANKS: 16
  ACACIA_PLANKS: 16
  DARK_OAK_PLANKS: 16
  MANGROVE_PLANKS: 16
  CHERRY_PLANKS: 16
  BAMBOO_PLANKS: 16
  CRIMSON_PLANKS: 16
  WARPED_PLANKS: 16
  
  # Wool & Dyes
  WHITE_WOOL: 2
  ORANGE_WOOL: 2
  MAGENTA_WOOL: 2
  LIGHT_BLUE_WOOL: 2
  YELLOW_WOOL: 2
  LIME_WOOL: 2
  PINK_WOOL: 2
  GRAY_WOOL: 2
  LIGHT_GRAY_WOOL: 2
  CYAN_WOOL: 2
  PURPLE_WOOL: 2
  BLUE_WOOL: 2
  BROWN_WOOL: 2
  GREEN_WOOL: 2
  RED_WOOL: 2
  BLACK_WOOL: 2
  
  # Glass
  GLASS: 4
  TINTED_GLASS: 4
  WHITE_STAINED_GLASS: 4
  ORANGE_STAINED_GLASS: 4
  MAGENTA_STAINED_GLASS: 4
  LIGHT_BLUE_STAINED_GLASS: 4
  YELLOW_STAINED_GLASS: 4
  LIME_STAINED_GLASS: 4
  PINK_STAINED_GLASS: 4
  GRAY_STAINED_GLASS: 4
  LIGHT_GRAY_STAINED_GLASS: 4
  CYAN_STAINED_GLASS: 4
  PURPLE_STAINED_GLASS: 4
  BLUE_STAINED_GLASS: 4
  BROWN_STAINED_GLASS: 4
  GREEN_STAINED_GLASS: 4
  RED_STAINED_GLASS: 4
  BLACK_STAINED_GLASS: 4
  
  # Terracotta
  TERRACOTTA: 2
  WHITE_TERRACOTTA: 2
  ORANGE_TERRACOTTA: 2
  MAGENTA_TERRACOTTA: 2
  LIGHT_BLUE_TERRACOTTA: 2
  YELLOW_TERRACOTTA: 2
  LIME_TERRACOTTA: 2
  PINK_TERRACOTTA: 2
  GRAY_TERRACOTTA: 2
  LIGHT_GRAY_TERRACOTTA: 2
  CYAN_TERRACOTTA: 2
  PURPLE_TERRACOTTA: 2
  BLUE_TERRACOTTA: 2
  BROWN_TERRACOTTA: 2
  GREEN_TERRACOTTA: 2
  RED_TERRACOTTA: 2
  BLACK_TERRACOTTA: 2
  
  # Concrete
  WHITE_CONCRETE: 2
  ORANGE_CONCRETE: 2
  MAGENTA_CONCRETE: 2
  LIGHT_BLUE_CONCRETE: 2
  YELLOW_CONCRETE: 2
  LIME_CONCRETE: 2
  PINK_CONCRETE: 2
  GRAY_CONCRETE: 2
  LIGHT_GRAY_CONCRETE: 2
  CYAN_CONCRETE: 2
  PURPLE_CONCRETE: 2
  BLUE_CONCRETE: 2
  BROWN_CONCRETE: 2
  GREEN_CONCRETE: 2
  RED_CONCRETE: 2
  BLACK_CONCRETE: 2
  
  # Plants & Flowers
  OAK_SAPLING: 1
  SPRUCE_SAPLING: 1
  BIRCH_SAPLING: 1
  JUNGLE_SAPLING: 1
  ACACIA_SAPLING: 1
  DARK_OAK_SAPLING: 1
  MANGROVE_PROPAGULE: 1
  CHERRY_SAPLING: 1
  DANDELION: 1
  POPPY: 1
  BLUE_ORCHID: 1
  ALLIUM: 1
  AZURE_BLUET: 1
  RED_TULIP: 1
  ORANGE_TULIP: 1
  WHITE_TULIP: 1
  PINK_TULIP: 1
  OXEYE_DAISY: 1
  CORNFLOWER: 1
  LILY_OF_THE_VALLEY: 1
  TORCHFLOWER: 2
  PITCHER_PLANT: 2
  PINK_PETALS: 1
  WILDFLOWER: 1
  CACTUS_FLOWER: 2
  BUSH: 1
  FIREFLY_BUSH: 3
  LEAF_LITTER: 1
  SHORT_DRY_GRASS: 1
  TALL_DRY_GRASS: 1
  
  # Crops & Food
  WHEAT: 4
  WHEAT_SEEDS: 2
  CARROT: 4
  POTATO: 4
  BEETROOT: 4
  BEETROOT_SEEDS: 2
  MELON: 4
  PUMPKIN: 4
  SUGAR_CANE: 4
  CACTUS: 4
  BAMBOO: 4
  KELP: 4
  SWEET_BERRIES: 4
  GLOW_BERRIES: 4
  COCOA_BEANS: 4
  APPLE: 4
  BREAD: 4
  COOKED_BEEF: 4
  COOKED_PORKCHOP: 4
  COOKED_CHICKEN: 4
  COOKED_MUTTON: 4
  COOKED_RABBIT: 4
  COOKED_COD: 4
  COOKED_SALMON: 4
  BAKED_POTATO: 4
  COOKIE: 4
  CAKE: 10
  PUMPKIN_PIE: 4
  
  # Mob Drops
  BONE: 10
  STRING: 4
  SPIDER_EYE: 4
  GUNPOWDER: 4
  ROTTEN_FLESH: 4
  SLIME_BALL: 4
  LEATHER: 4
  FEATHER: 4
  RABBIT_HIDE: 4
  RABBIT_FOOT: 4
  PHANTOM_MEMBRANE: 30
  PRISMARINE_SHARD: 30
  PRISMARINE_CRYSTALS: 30
  SCUTE: 30
  ECHO_SHARD: 600
  DISC_FRAGMENT_5: 100
  
  # Nether Items
  GLOWSTONE_DUST: 2
  MAGMA_CREAM: 3
  NETHER_WART: 3
  CRIMSON_FUNGUS: 2
  WARPED_FUNGUS: 2
  SOUL_SAND: 1
  SOUL_SOIL: 1
  SHROOMLIGHT: 3
  CRYING_OBSIDIAN: 5
  
  # End Items
  CHORUS_FRUIT: 2
  POPPED_CHORUS_FRUIT: 3
  PURPUR_BLOCK: 2
  END_ROD: 3
  SHULKER_BOX: 100
  
  # Redstone & Tech
  REDSTONE_BLOCK: 30
  REDSTONE_TORCH: 6
  REPEATER: 10
  COMPARATOR: 12
  OBSERVER: 16
  PISTON: 10
  STICKY_PISTON: 12
  HOPPER: 15
  DROPPER: 8
  DISPENSER: 8
  FURNACE: 4
  BLAST_FURNACE: 10
  SMOKER: 10
  CRAFTING_TABLE: 2
  CRAFTER: 50
  CHEST: 4
  BARREL: 4
  LECTERN: 5
  COMPOSTER: 3
  CAULDRON: 8
  ANVIL: 30
  ENCHANTING_TABLE: 100
  BREWING_STAND: 20
  ENDER_CHEST: 80
  
  # Copper Blocks (1.21 additions)
  COPPER_BLOCK: 18
  CUT_COPPER: 18
  COPPER_GRATE: 18
  COPPER_BULB: 20
  COPPER_DOOR: 20
  COPPER_TRAPDOOR: 20
  CHISELED_COPPER: 18
  EXPOSED_COPPER: 18
  WEATHERED_COPPER: 18
  OXIDIZED_COPPER: 18
  WAXED_COPPER_BLOCK: 20
  
  # Tuff Variants (1.21)
  TUFF_STAIRS: 1
  TUFF_SLAB: 1
  TUFF_WALL: 1
  TUFF_BRICKS: 2
  CHISELED_TUFF: 2
  CHISELED_TUFF_BRICKS: 2
  POLISHED_TUFF: 2
  POLISHED_TUFF_STAIRS: 2
  POLISHED_TUFF_SLAB: 2
  POLISHED_TUFF_WALL: 2
  
  # Misc Building Blocks
  BRICKS: 3
  STONE_BRICKS: 2
  MOSSY_STONE_BRICKS: 2
  CRACKED_STONE_BRICKS: 2
  CHISELED_STONE_BRICKS: 2
  DEEPSLATE_BRICKS: 2
  DEEPSLATE_TILES: 2
  PRISMARINE: 5
  PRISMARINE_BRICKS: 5
  DARK_PRISMARINE: 5
  PURPUR_PILLAR: 3
  QUARTZ_BLOCK: 12
  QUARTZ_PILLAR: 12
  CHISELED_QUARTZ_BLOCK: 12
  SMOOTH_QUARTZ: 12
  SANDSTONE: 2
  RED_SANDSTONE: 2
  OBSIDIAN: 8
  BEDROCK: 9000000
  
  # Utility Items
  BUCKET: 6
  WATER_BUCKET: 6
  LAVA_BUCKET: 15
  MILK_BUCKET: 5
  POWDER_SNOW_BUCKET: 6
  BOWL: 1
  BOTTLE: 1
  GLASS_BOTTLE: 1
  COMPASS: 8
  CLOCK: 8
  MAP: 5
  SPYGLASS: 10
  BUNDLE: 5
  SHEARS: 4
  FLINT_AND_STEEL: 5
  LEAD: 3
  NAME_TAG: 15
  SADDLE: 20
  
  # Pottery & Smithing Templates
  POTTERY_SHARD_ANGLER: 10
  POTTERY_SHARD_ARCHER: 10
  POTTERY_SHARD_ARMS_UP: 10
  POTTERY_SHARD_BLADE: 10
  POTTERY_SHARD_BREWER: 10
  POTTERY_SHARD_BURN: 10
  POTTERY_SHARD_DANGER: 10
  POTTERY_SHARD_EXPLORER: 10
  POTTERY_SHARD_FRIEND: 10
  POTTERY_SHARD_HEART: 10
  POTTERY_SHARD_HEARTBREAK: 10
  POTTERY_SHARD_HOWL: 10
  POTTERY_SHARD_MINER: 10
  POTTERY_SHARD_MOURNER: 10
  POTTERY_SHARD_PLENTY: 10
  POTTERY_SHARD_PRIZE: 10
  POTTERY_SHARD_SHEAF: 10
  POTTERY_SHARD_SHELTER: 10
  POTTERY_SHARD_SKULL: 10
  POTTERY_SHARD_SNORT: 10
  NETHERITE_UPGRADE_SMITHING_TEMPLATE: 200
  SENTRY_ARMOR_TRIM_SMITHING_TEMPLATE: 30
  VEX_ARMOR_TRIM_SMITHING_TEMPLATE: 30
  WILD_ARMOR_TRIM_SMITHING_TEMPLATE: 30
  COAST_ARMOR_TRIM_SMITHING_TEMPLATE: 30
  DUNE_ARMOR_TRIM_SMITHING_TEMPLATE: 30
  WAYFINDER_ARMOR_TRIM_SMITHING_TEMPLATE: 30
  RAISER_ARMOR_TRIM_SMITHING_TEMPLATE: 30
  SHAPER_ARMOR_TRIM_SMITHING_TEMPLATE: 30
  HOST_ARMOR_TRIM_SMITHING_TEMPLATE: 30
  WARD_ARMOR_TRIM_SMITHING_TEMPLATE: 30
  SILENCE_ARMOR_TRIM_SMITHING_TEMPLATE: 30
  TIDE_ARMOR_TRIM_SMITHING_TEMPLATE: 30
  SNOUT_ARMOR_TRIM_SMITHING_TEMPLATE: 30
  RIB_ARMOR_TRIM_SMITHING_TEMPLATE: 30
  EYE_ARMOR_TRIM_SMITHING_TEMPLATE: 30
  SPIRE_ARMOR_TRIM_SMITHING_TEMPLATE: 30
  FLOW_ARMOR_TRIM_SMITHING_TEMPLATE: 30
  BOLT_ARMOR_TRIM_SMITHING_TEMPLATE: 30
  
  # Armor Pieces
  LEATHER_HELMET: 2
  LEATHER_CHESTPLATE: 3
  LEATHER_LEGGINGS: 3
  LEATHER_BOOTS: 2
  CHAINMAIL_HELMET: 8
  CHAINMAIL_CHESTPLATE: 10
  CHAINMAIL_LEGGINGS: 9
  CHAINMAIL_BOOTS: 8
  IRON_HELMET: 12
  IRON_CHESTPLATE: 24
  IRON_LEGGINGS: 21
  IRON_BOOTS: 12
  GOLDEN_HELMET: 15
  GOLDEN_CHESTPLATE: 30
  GOLDEN_LEGGINGS: 27
  GOLDEN_BOOTS: 15
  DIAMOND_HELMET: 200
  DIAMOND_CHESTPLATE: 400
  DIAMOND_LEGGINGS: 350
  DIAMOND_BOOTS: 200
  NETHERITE_HELMET: 2000
  NETHERITE_CHESTPLATE: 4000
  NETHERITE_LEGGINGS: 3500
  NETHERITE_BOOTS: 2000
  TURTLE_HELMET: 100
  
  # Additional Ores & Blocks
  DIAMOND_ORE: 200
  DEEPSLATE_DIAMOND_ORE: 200
  EMERALD_ORE: 80
  DEEPSLATE_EMERALD_ORE: 8000
  IRON_ORE: 3
  DEEPSLATE_IRON_ORE: 3
  GOLD_ORE: 5
  DEEPSLATE_GOLD_ORE: 5
  COAL_ORE: 1
  DEEPSLATE_COAL_ORE: 1
  COPPER_ORE: 2
  DEEPSLATE_COPPER_ORE: 2
  LAPIS_ORE: 4
  DEEPSLATE_LAPIS_ORE: 4
  REDSTONE_ORE: 2
  DEEPSLATE_REDSTONE_ORE: 2
  NETHER_QUARTZ_ORE: 3
  NETHER_GOLD_ORE: 5
  AMETHYST_CLUSTER: 10
  BUDDING_AMETHYST: 50
  
  # Storage Blocks
  DIAMOND_BLOCK: 2250
  EMERALD_BLOCK: 720
  IRON_BLOCK: 27
  GOLD_BLOCK: 45
  COAL_BLOCK: 9
  COPPER_BLOCK: 18
  LAPIS_BLOCK: 36
  REDSTONE_BLOCK: 18
  QUARTZ_BLOCK: 12
  AMETHYST_BLOCK: 16
  NETHERITE_BLOCK: 22500
  
  # Eggs & Spawn Items
  EGG: 1
  BLUE_EGG: 3
  BROWN_EGG: 3
  
  # Additional Food
  BEEF: 2
  PORK_CHOP: 2
  CHICKEN: 2
  MUTTON: 2
  RABBIT: 2
  COD: 1
  SALMON: 2
  TROPICAL_FISH: 2
  PUFFERFISH: 3
  DRIED_KELP: 1
  SUSPICIOUS_STEW: 4
  MUSHROOM_STEW: 3
  RABBIT_STEW: 4
  BEETROOT_SOUP: 2
  HONEY_BOTTLE: 3
  
  # Additional Nether & End
  NETHERITE_UPGRADE_SMITHING_TEMPLATE: 200
  ENDER_EYE: 25
  BLAZE_POWDER: 10
  MAGMA_BLOCK: 3
  GLOWSTONE: 8
  RESPAWN_ANCHOR: 50
  LODESTONE: 40

# Crates-Konfiguration - ARMOR ONLY (No Weapons/Tools)
# Pool-Eintr├ñge: "MATERIAL:amount:weight"  -> weight ist optional, wird f├╝r die gewichtete Auswahl genutzt
# Guaranteed: Liste von garantierten Eintr├ñgen (Format: MATERIAL:amount oder MATERIAL:amount:namedWorthKey)
# Bundles: Optional; Items in einem Bundle mit Semikolon getrennt, z. B. "GOLD_INGOT:10;EMERALD:2"
crates:
  basic:
    display: "┬ºaÔ£ª Basis-Kiste Ô£ª"
    key: "Basic Key"
    tier: "basic"
    guaranteed:
      - "IRON_HELMET:1"
    animation:
      ticks: 2
      cycles: 30
    pool:
      - "DIAMOND_HELMET:1:40"
      - "DIAMOND_CHESTPLATE:1:35"
      - "DIAMOND_LEGGINGS:1:35"
      - "DIAMOND_BOOTS:1:40"
    
    bundles:
      - "IRON_INGOT:5;COAL:10"

  rare:
    display: "┬º5Ô£ª Seltene Kiste Ô£ª"
    key: "Rare Key"
    tier: "rare"
    guaranteed:
      - "DIAMOND_HELMET:1"
    animation:
      ticks: 2
      cycles: 45
    pool:
      - "DIAMOND_HELMET:1:40"
      - "DIAMOND_CHESTPLATE:1:30"
      - "DIAMOND_LEGGINGS:1:30"
      - "DIAMOND_BOOTS:1:40"
    bundles:
      - "DIAMOND:2;EMERALD:3"

  legendary:
    display: "┬º6Ô£ª Legend├ñre Kiste Ô£ª"
    key: "Legend Key"
    tier: "legendary"
    guaranteed:
      - "NETHERITE_CHESTPLATE:1"
    animation:
      ticks: 3
      cycles: 80
    pool:
      - "NETHERITE_HELMET:1:35"
      - "NETHERITE_CHESTPLATE:1:30"
      - "NETHERITE_LEGGINGS:1:30"
      - "NETHERITE_BOOTS:1:35"
      - "ELYTRA:1:8"
      - "TOTEM_OF_UNDYING:1:12"
    bundles:
      - "DIAMOND:5;EMERALD:8;GOLD_INGOT:10"
      - "NETHERITE_SCRAP:2;DIAMOND:4"

# Enchantment-Worth-Multiplikatoren (pro Enchant-Level)
worth-enchant-multipliers:
  DAMAGE_ALL: 200
  DURABILITY: 50
  ARROW_DAMAGE: 120
  KNOCKBACK: 80
  FIRE_ASPECT: 150
  SHARPNESS: 180
  PROTECTION: 100
  EFFICIENCY: 60
  FORTUNE: 300
  LOOTING: 250
  SILK_TOUCH: 500
  MENDING: 800
  INFINITY: 400
  THORNS: 100
  DEPTH_STRIDER: 75
  FROST_WALKER: 150
  SOUL_SPEED: 200
  SWIFT_SNEAK: 250

# Named-Worth (spezifische Items mit Display-Namen)
# Unterst├╝tzung f├╝r zwei Formate:
# 1) "MATERIAL|DisplayName": wert
# 2) "KEY": wert (kann in Crates als namedWorthKey verwendet werden, z. B. LEGEND_SWORD)
worth-named:
  "DIAMOND_SWORD|┬º6Legend├ñres Schwert": 5000
  "ENCHANTED_GOLDEN_APPLE|┬º5Glitzernder Apfel": 4000
  "LEGEND_SWORD": 12000 # benutzerdefinierter named-worth-key

messages:
  prefix: "&6&lÔÜí&r &e"
  no-permission: "&cDu hast keine Berechtigung daf├╝r."
  not-enough-money: "&cDu hast nicht genug Geld."
  not-enough-shards: "&cDu hast nicht genug Shards."
  sold-all: "&aÔ£ô &fArtikel verkauft! Erhalten: &a$%amount%"
  paid-player: "&aÔ£ô &fDu hast &e%player% &f$%amount% bezahlt."
  received-payment: "&aÔ£ô &fDu hast &a$%amount% &fvon &e%player% &ferhalten."
  balance: "&eGuthaben: &a$%amount%"
  shards: "&5Shards: &d%amount%"
  kills: "&cKills: &f%amount%"
  crate-opened: "&aÔ£ô &fKiste ge├Âffnet! Erhalten: &e%items%"
  warp-teleport: "&aÔ£ô &fTeleportiert zu &e%warp%"
  auction-listed: "&aÔ£ô &fItem im Auktionshaus gelistet f├╝r &a$%price%"
  auction-bought: "&aÔ£ô &fItem gekauft f├╝r &a$%price%"
  auction-expired: "&cÔ£ù &fDeine Auktion ist abgelaufen: &e%item%"
  order-created: "&aÔ£ô &fOrder erstellt: &e%amount%x %item% &ff├╝r &a$%price%/St├╝ck"
  order-delivered: "&aÔ£ô &f%amount%x geliefert! Verdient: &a$%earned%"
data-file: data.yml
